name: Pipeline

on:
  push:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run ESLint (Code Check Test)
        run: npm run eslint

      - name: Run Snyk (Security Check Test)
        run: npm run snyk

      - name: SSH into EC2 instance and update project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd /home/ubuntu
            cd /home/ubuntu/Abschluss-Projekt
            npm run stop
            cd /home/ubuntu
            sudo kill $(sudo lsof -t -i:3000)
            rm -rf Abschluss-Projekt
            git clone https://github.com/Flamur64/Abschluss-Projekt.git
            cd /home/ubuntu/Abschluss-Projekt
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
            npm install
            NODE_OPTIONS='--no-warnings' npm run start
