name: pipeline

on:
  push:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run ESLint (Code Check Test)
        run: npm run eslint

      - name: Run Snyk (Security Check Test)
        run: npm run snyk

      - name: Run Server
        run: npm run server